baseURL: "https://ваш-username.github.io/"  # Для GitHub Pages
defaultContentLanguage: "ru"               # Язык по умолчанию
defaultContentLanguageInSubdir: true       # URL вида /ru/, /en/

languages:
  en:
    languageName: "English"
    contentDir: "content/en"
    weight: 1
  ru:
    languageName: "Русский"
    contentDir: "content/ru"
    weight: 2